# Generated by Django 4.1.7 on 2023-02-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1800, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=80, verbose_name='Наименование')),
                ('description', models.TextField(default='Description', max_length=1800, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('price', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Стоимость')),
                ('image', models.TextField(default='Image', max_length=1000, verbose_name='Изоброжение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='webapp.category', verbose_name='Категория')),
            ],
        ),
    ]
