# Generated by Django 4.1.7 on 2023-02-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='webapp.category', verbose_name='Категория'),
        ),
    ]
